import Navbar from "../../components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={"max-w-6xl mx-auto rounded-2xl bg-black text-white"}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
